#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

for config_file in $(ls $HOME/.dotfiles/zsh/*.zsh)
do
  source $config_file
done

#export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
source $(rvm 2.3 do rvm env --path)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

_direnv_hook() {
  eval "$(direnv export zsh)";
}
typeset -ag precmd_functions
if [[ -z $precmd_functions[(r)_direnv_hook] ]]; then
  precmd_functions+=_direnv_hook;
fi
