#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

for config_file in $(ls $HOME/.dotfiles/zsh/*.zsh)
do
  source $config_file
done

# Customize to your needs...

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

eval "$(direnv hook zsh)"
